# Gemfile

source 'https://rubygems.org'
ruby "2.2.1"

# Used for API calls
gem 'httparty', "~> 0.13.5"
# Used for serving, dancing, and crooning.
gem "sinatra", "~> 1.4.6"
# Used to remove leaves from your yard.
gem 'rake'

group :development, :test do
# Used for testing
  gem 'jasmine'
end